package src.core.Emitter;

public enum Actions {
    START,
    CLEAR,
    CONTINUE,
    UPDATE_TIME,

    IS_SHOW_TIME,
    IS_SHOW_STATS,
    CHANGE_LIFETIME_CAR,
    CHANGE_LIFETIME_BIKE,
    SHOW_CURRENT_TRANSPORT,
    IS_MOVEMENT_CAR,
    IS_MOVEMENT_BIKE,
    CHANGE_PRIORITY_THREAD_CAR,
    CHANGE_PRIORITY_THREAD_BIKE,
    DELETE_BIKES,
    SAVE,
    LOAD
}
