package Clasess.Emitter;

public enum Actions {
    START,
    STOP,
    UPDATE_TIME,
    SHOW_TIME,
    HIDE_TIME,
    SHOW_STATS,
    HIDE_STATS,
    MODAL_CANCEL,
    CHANGE_LIFETIME_CAR,
    CHANGE_LIFETIME_BIKE,
    SHOW_CURRENT_TRANSPORT,
    MOVEMENT_CAR_TRUE,
    MOVEMENT_CAR_FALSE,
    MOVEMENT_BIKE_TRUE,
    MOVEMENT_BIKE_FALSE,
    CHANGE_PRIORITY_THREAD_CAR,
    CHANGE_PRIORITY_THREAD_BIKE
}
